language: python
python:
  - "2.6"
  - "2.7"
services:
  - rabbitmq
  - memcached
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libsnappy-dev
install:
  - "pip install -r tools/test-requires --use-mirrors"
  - "python setup.py develop"
script: "python setup.py nosetests"