language: python
python:
  - "2.6"
  - "2.7"
services:
  - rabbitmq
  - memcached
install: "pip install -r tools/test-requires --use-mirrors"
before_script: "python setup.py develop"
script: "python setup.py nosetests"