language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
services:
  - rabbitmq
  - memcached
install:
  - "pip install . --use-mirrors"
  - "pip install -r tools/test-requires --use-mirrors"
script: nosetests