language: python
python:
  - "2.6"
  - "2.7"
services:
  - rabbitmq
  - memcached
before_install:
  - sudo apt-get update -qq
install:
  - "pip install -r tools/test-requires --use-mirrors"
  - "pip install -e git+http://github.com/openstack/oslo.messaging#egg=oslo.messaging --use-mirrors"
  - "python setup.py develop"
script: "python setup.py nosetests"